version: "3.9"
services:
  app:
    build: .
    platform: "linux/i386"
    env_file:
      - .env
    volumes:
      - .:/home/app
    command: |
      bash
    tty: true
    stdin_open: true
    cap_add:
      - "SYS_PTRACE"
